name: appui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0



environment:
  sdk: ^3.5.1

dependencies:
  flutter_svg: ^2.0.17
  flutter:
    sdk: flutter
  grpc: ^4.0.4
  protoc_plugin: ^22.0.1
  protobuf: ^4.0.0
  provider: ^6.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/
      - assets/icons/
      - assets/imgs/